apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/njalv/argo-cd-test.git
    targetRevision: main
    path: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
