apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: resourcegroup.azure.platform
  labels:
    provider: azure
    type: resourcegroup
    platformAPI: platform.localhost
spec:
  compositeTypeRef:
    apiVersion: platform.localhost/v1alpha1
    kind: XResourceGroup
  resources:
    - name: composedAzureResourceGroup
      base:
        apiVersion: azure.upbound.io/v1beta1
        kind: ResourceGroup
        spec:
          forProvider:
            tags:
              managed-by: "crossplane-platform"
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.commonTags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.uid
            strategy: string
            string:
              fmt: "azure-providerconfig"
          toFieldPath: spec.providerConfigRef.name
