apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xresourcegroups.platform.localhost
spec:
  group: platform.localhost
  names:
    kind: XResourceGroup
    plural: xresourcegroups
  claimNames:
    kind: ResourceGroupClaim
    plural: resourcegroupclaims
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              description: "Specification for creating a platform-standard Azure Resource Group."
              properties:
                location:
                  type: string
                  description: "Azure region for the Resource Group (e.g., WestEurope, EastUS)."

                  type: object
                  description: "Common tags to apply."
                  properties:
                    environment:
                      type: string
                      description: "e.g., dev, staging, prod"
                      default: "dev" 
                    project:
                      type: string
                      description: "Project identifier"
                  required:
                    - project
              required:
                - location
                - commonTags